blog/urls.py
from django.urls import path  # type: ignore
from django.conf.urls.static import static  # type: ignore
from blog import views
from django_portafolio import settings  # type: ignore


app_name = 'blog'  # para referenciar a todas las urls del blog

urlpatterns = [
    path('', views.posts, name='posts'),
    path('<int:post_id>/', views.post_detail,
         name='post_detail'),  # <int:post_id>
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

django_portafolio/urls.py
from django.contrib import admin  # type: ignore
from django.urls import path,include  # type: ignore
from django.conf import settings # type: ignore
from django.conf.urls.static import static # type: ignore
from portafolio import views
#from blog import urls
#from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('blog/', include('blog.urls')),# para incluir las urls de la app de blog
]

""" if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT) # poner si o si para no tener problemas con imagenes
 """

blog/models.py
from django.db import models  # type: ignore
import datetime
from cloudinary.models import CloudinaryField  # type: ignore
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField(max_length=1000)
    #image = models.ImageField(upload_to='blog/images')
    image = CloudinaryField('image' ,blank=True, null=True,default="https://res.cloudinary.com/tu_cloud_name/image/upload/v12345678/default_image.jpg")

    # si no le paso una feha, coloca la fecha actual
    date = models.DateField(datetime.date.today)

    def __str__(self):  # metodo __str__ para retornar el los atributos del objecto
        return self.title  # retorna el nombre

portafolio/models.py
from django.db import models  # type: ignore
from cloudinary.models import CloudinaryField  # type: ignore
# Create your models here.
# clase para proyecto


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    #image = models.ImageField(upload_to='portafolio/images')
    url = models.URLField(blank=True)
    url2 = models.URLField(blank=True)
    image = CloudinaryField('image' ,blank=True, null=True,default="https://res.cloudinary.com/tu_cloud_name/image/upload/v12345678/default_image.jpg")

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404  # type: ignore
from .models import Post
# Create your views here.

# pagina de post


def posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})


def post_detail(request, post_id):
    # toma primero el modelo,Post. y luego el post_id en primary key
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {'post': post})  # type: ignore

portafolio/views.py
import os
from django.shortcuts import render #type: ignore
from .models import Project

from django.contrib.auth.models import User # type: ignore



# Create your views here.
def home(request):
    projects=Project.objects.all()
    return render(request,'home.html',{'projects':projects})

blog/templates/post_detail.html
{% extends "base.html" %} {% block content %}

<div class="text-center">
  <h1>{{ post.title }}</h1>
  <h3 class="my-5 h5">{{post.date|date:'d M Y'}}</h3>
  <img src="{{post.image.url}}" alt="{{post.title}}" />
  <div class="mg-4 img-fluid">
    <p>{{post.content|safe}}</p>
    <!--truncatechars:100 para mostrar solo cien caracteres-->
  </div>
</div>

{% endblock content %}

blog/templates/posts.html
{% extends "base.html" %} {% block content%}
<h1 class="text-center d-4">Posts</h1>
{% for post in posts %}
<div class="p-3">
  <div class="card card-body bg-black">
    <div class="row">
      <div class="col-3">
        <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}" />
      </div>
      <div class="col-9">
        <h1>{{ post.title }}</h1>
        <p>{{post.content|striptags|truncatechars:100}}</p>
        <h3>{{post.date|date:'d M Y'}}</h3>

        <a class="btn btn-primary" href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a>
      </div>
    </div>
  </div>
</div>
{% endfor %} {% endblock content%}

portafolio/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "main.css" %}">
    <title>Mi Portafolio</title>
</head>
<body class="text-light">
    {% include "partials/navbar.html" %}
    
    <div class="container p-4">
        {% block content %}
        {% endblock  %}
    </div>


    <footer></footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

portafolio/templates/home.html
{% extends "base.html" %}
 {% block content %}
 {% load static %}
<header class="row my-auto bgdark pt-4">
    <div class="col-md-4">

    <img src="{% static "portafolio/profile.jpg" %}" alt="profile" width="350" heigt="350">
    </div>


    <div class="col-md-8">
        <h1>I am <strong>Rodrigo Quiroga</strong></h1>
        <h3>I Python Developer</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit neque doloribus similique iste eos dolorum natus sed facere, praesentium tempora, minima, possimus eveniet enim consequatur saepe? Iusto repudiandae qui eaque!</p>
        <a class="btn btn-primary btn-lg rounden-0 my-3" href="{% static "portafolio/cv_ejemplo.pdf" %}"target="_blank">Download CV</a>
    </div>
</header>


 <div class="row my-4 text-center">
        <h3>My Projects</h3>
        <p>Proyectos que hice</p>
        {% for project in projects%}
            <div class="col-md-4">
                <div class="card bgdark pd-4 card-project">
                    <img src="{{project.image.url}}" alt="aaas" class="card-img-top" />
                    <div class="card-body">
                        <h2>{{project.title}}</h2>
                        <p>{{project.description}}</p>
                        {% if project.url %}
                            <!--valida que la url exista-->
                            <a target="_blank" class="btn btn-light rounder-0 btn-sm" href="{{project.url}}">{{project.url}}</a>
                            <a target="_blank" class="btn btn-light rounder-0 btn-sm mt-2" href="{{project.url2}}">{{project.url2}}</a>
                        {% endif %} 
                    </div>
                </div>
            </div>
        {% endfor %} 
       
 </div>
{% endblock content %}

portafolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand fw-bold fst-italic" href="/">RQ</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">

        <li class="nav-item">
          <a class="nav-link" href="{% url "blog:posts" %}">Blog</a>
        </li>
        <li class="nav-item d-flex align-items-center">
          <a class="btn btn-primary btn-sm" href="{% static "portafolio/cv_ejemplo.pdf" %}"target="_blank">Download CV</a>
        </li>
       
      </ul>
    </div>
  </div>
</nav>